feat: add a way to change out the main form type
araise-dev/CrudBundle pull request #70
Opened 2024-07-11 12:02 UTC by Ruesa18

References: https://dev.whatwedo.ch/araise/araise-meta/-/issues/125

2024-07-11 12:05 UTC, tuxes3 submitted a review, later dismissed

2024-07-11 12:07 UTC, tuxes3 requested changes
something is funky with the tests

2024-07-11 13:06 UTC, Ruesa18 commented
@tuxes3 I think, for some reason, the `configureOptions()` is not being called before the `getCreateForm()`... But only in the tests? I did not have a problem with that in the browser yet...
A quick-fix would be to make the following change:
```php
public function getMainFormType(): string
{
    return array_key_exists(self::OPT_MAIN_FORM_TYPE, $this->options) ? $this->options[self::OPT_MAIN_FORM_TYPE] : FormType::class;
}
```
But I don't really like this option because we wouldn't need the options anymore... So we could also just do:
```php
public function getMainFormType(): string
{
    return FormType::class;
}
```

And then just overwrite this method if we need it

2024-07-11 13:36 UTC, tuxes3 commented
> @tuxes3 I think, for some reason, the `configureOptions()` is not being called before the `getCreateForm()`... But only in the tests? I did not have a problem with that in the browser yet... A quick-fix would be to make the following change:

@Ruesa18 We need to find out why it isn't called in the tests. If you want i can investigate that more ... let me know

2024-07-15 18:24 UTC, tuxes3 approved these changes

2024-07-15 18:29 UTC, merged